#!/bin/bash
# Service remover script for services;

if [[ $EUID -ne 0 ]]; then
	echo "This script must be run as root" 
	exit 1
fi

function usage(){
	echo """usage: 
	srv-rm -n <name of service> 

	example:

	sudo ./service-gen -n ss-libev-41116 
	"""	
	exit 1
}

while getopts n:d:e:wh flag
do
	case "${flag}" in
		(n) name=${OPTARG};;
		(p) srvpath=${OPTARG};;
		# (d) description=${OPTARG};;
		# (e) execute=${OPTARG};;
		# (w) directory=${OPTARG};;
	(h) usage;;
	(*) usage
		exit;;

	esac
done


if [[ -z "$name" ]]; then # || -z "$directory" ]]; then
	echo "Missing Search Name"
else
	if [[ -z "$srvpath" ]]; then
		srvpath="/etc/systemd/system/"
	fi

	search=( "$(ls $srvpath | grep -i $name)" )

	if [[ -z "$search" ]]; then
		echo "No service with matching name to $name"
	else	
		tester=( $search )
		echo "Found Object(s) count ${#tester[@]}"
		

			count=0
			for object in $search; do 
				all[$count]="$object"
				((count++))
				echo "$count) $object"
			done
			echo "Enter which service you want to remove: "
			read input
			if [[ -n ${input//[0-9]/} || $input -gt $count  ]]; then
				echo "Bad input, exiting..."
				exit 1
			else
				selectsrv="${all[(($input-1))]}"
				echo "Selected service is $selectsrv"
			fi

		while true; do
	 		read -p "Are you sure you want to delete service $selectsrv? [yN]" yn
			yn=${yn:-n}
	 		case $yn in
	 			[Yy]* ) break;;
	 			[Nn]* ) echo "Exiting"; exit 1;;
	 		esac
	 	done

		while true; do
	 		read -p "Are you a 100% SURE to DELETE $selectsrv? [yN]" yn
			yn=${yn:-n}
	 		case $yn in
	 			[Yy]* ) systemctl stop $selectsrv; systemctl disable $selectsrv;
					rm -f "${srvpath}${selectsrv}"
					if [[ $? -eq "0" ]]; then
						echo "Operation was successful"
					else
						echo "Delete was not successful"
					fi
				 	break;;
	 			[Nn]* ) echo "Exiting"; exit 1;;
	 		esac
	 	done
		systemctl daemon-reload
	fi
fi

exit 0

