#!/bin/bash
# Basic Generator script for services;

while getopts u:a:f: flag
do
	case "${flag}" in
		u) username=${OPTARG};;
		a) age=${OPTARG};;
		f) fullname=${OPTARG};;
	esac
done


if [[ -z "$username" || -z "$age" || -z "$fullname" ]]; then
	echo "Missing Arguments"
else
	echo "Username: $username";
	echo "Age: $age";
	echo "Full Name: $fullname";
fi
